-- ============================================================
-- Claude Crypto Bot — Coin Research Schema (v2 migration)
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- Run AFTER supabase_schema.sql
-- ============================================================

-- Research reports generated by Claude Opus for new/trending coins
CREATE TABLE IF NOT EXISTS coin_research (
    id              UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),

    -- Identity
    coin_id         TEXT        NOT NULL,    -- CoinGecko ID (e.g. "render-token")
    symbol          TEXT        NOT NULL,    -- e.g. "RNDR"
    name            TEXT        NOT NULL,    -- e.g. "Render Network"
    category        TEXT,                   -- e.g. "AI & Big Data"

    -- Claude's verdict
    investment_score    INTEGER,            -- 0–100 overall score
    team_score          INTEGER,            -- 0–20
    technology_score    INTEGER,            -- 0–20
    market_score        INTEGER,            -- 0–20
    tokenomics_score    INTEGER,            -- 0–20
    usecase_score       INTEGER,            -- 0–20
    verdict         TEXT,                   -- 'buy' | 'watch' | 'avoid'
    suggested_usd   NUMERIC(10,2),          -- recommended position size
    hold_months     INTEGER,
    risks           JSONB,                  -- ["risk 1", "risk 2", ...]
    opportunities   JSONB,                  -- ["opp 1", "opp 2", ...]
    summary         TEXT,                   -- Claude's narrative paragraph

    -- Market snapshot at time of research
    price_usd       NUMERIC(20,8),
    market_cap_usd  NUMERIC(20,2),
    volume_24h_usd  NUMERIC(20,2),
    price_change_7d NUMERIC(8,2),
    github_commits_4w INTEGER,
    twitter_followers INTEGER,

    -- Raw CoinGecko data blob (for future re-analysis)
    raw_data        JSONB,

    -- Tracking
    on_watchlist    BOOLEAN     DEFAULT FALSE,
    actioned        BOOLEAN     DEFAULT FALSE,  -- user has manually acted on this
    notes           TEXT                        -- user's own notes via /note command
);

-- Watchlist: coins the user has saved for monitoring
CREATE TABLE IF NOT EXISTS coin_watchlist (
    id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    coin_id     TEXT        NOT NULL UNIQUE,
    symbol      TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    entry_price NUMERIC(20,8),               -- price when added to watchlist
    target_usd  NUMERIC(10,2),               -- how much to invest if confirmed
    research_id UUID        REFERENCES coin_research(id),
    active      BOOLEAN     DEFAULT TRUE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_coin_research_symbol    ON coin_research (symbol);
CREATE INDEX IF NOT EXISTS idx_coin_research_verdict   ON coin_research (verdict, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_coin_research_score     ON coin_research (investment_score DESC);
CREATE INDEX IF NOT EXISTS idx_coin_watchlist_active   ON coin_watchlist (active, created_at DESC);
